# Spring Boot应用程序配置
spring:
  application:
    name: dubbo-server
  main:
    allow-bean-definition-overriding: true
server:
  port: 8087

# Dubbo配置
dubbo:
  application:
    name: dubbo-server
    qos-port: 33333
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1